container:
  image: lapeevvd/microservice-architecture
  version: latest
  port: 8080

deployment:
  replicaCount: 1 # unfortunately vm can't support 2 application pods + db-pod, so replicaCount set to 1

service:
  port: 8000

ingress:
  host: arch.homework
  path: /

postgresql:
  enabled: true
  postgresqlDatabase: microservice-architecture-db
  postgresqlUsername: postgres
  postgresqlPassword: postgres