apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config-map
data:
  DATABASE_URL: jdbc:postgresql://{{ include "postgresql.fullname" . }}:5432/microservice-architecture-db
  DATABASE_USER: postgres
