apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}-deployment
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.container.image }}:{{ .Values.container.version }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - configMapRef:
                name: {{ include "helm-chart.fullname" . }}-config-map
            - secretRef:
                name: {{ include "helm-chart.fullname" . }}-secret
          livenessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: /
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: {{ .Values.container.port }}
              path: /health
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 2