apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-service
spec:
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: NodePort